# /etc/nginx/conf.d/moxcode.conf
server {
    listen 80;
    listen [::]:80;
    server_name moxcode.ruthgracewong.com;

    location ~ /.well-known {
        root /var/www/moxcode/static;
        allow all;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name moxcode.ruthgracewong.com;
    ssl_certificate /etc/letsencrypt/live/moxcode.ruthgracewong.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/moxcode.ruthgracewong.com/privkey.pem;

    location / {
        proxy_pass         http://127.0.0.1:8787;
        proxy_set_header   Host $host;
        proxy_set_header   X-Forwarded-Proto https;
        proxy_read_timeout 15s;
    }
}
