# /etc/nginx/conf.d/moxcode.conf (temporary, http-only for certbot)
server {
    listen 80;
    listen [::]:80;
    server_name moxcode.ruthgracewong.com;

    location ~ /.well-known {
        root /var/www/moxcode/static;
        allow all;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
